### ISSUE TITLE
 purpose of OAuthLogin??

### ISSUE THREAD

**Issue by iiitmahesh** [rationalappdev/react-native-oauth-login-tutorial#2]
I am trying to implement custom SOS(single sign on) like google,facebook... etc for my applciations.
how to use this to do soz//  

Can I use in any other option to do this?? 
what purpose of this following.(is it for "to close webview and redirect to app" , Am I correct please correct me where I was wrong here??) 

> res.redirect('OAuthLogin://login?user=' + JSON.stringify(req.user)));

**Comment by ashishnumino** [comment]
yes @iiitmahesh `res.redirect('OAuthLogin://login?user=' + JSON.stringify(req.user)));` is a browser redirect to the app.

the part of the android manifest xml because of which the browser is able to redirect to app is as follows:
```
<intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="oauthlogin" android:host="login" />
        </intent-filter>
```

you ll have to create an intent filter in activity tag of android manifest file.
you can refer [this](http://rationalappdev.com/logging-into-react-native-apps-with-facebook-or-google) link
